### ISSUE TITLE
this script stopped working.....

### ISSUE THREAD

**Issue by JemmySailesh** [arapurayil/utube#4]
https://utube.arapurayil.com/stream/UCP0uG-mcMImgKnJz-VjJZmQ/master.m3u8    script is not working, shows error 

TypeError: Cannot read properties of null (reading '0')
    at worker.js:10:60
    at async hlsUrl (worker.js:8:10)
    at async handleRequest (worker.js:42:11)

**Comment by arapurayil** [comment]
Working for me. Could be a cloudflare edge issue. Can you try again?
