### ISSUE TITLE
Not working. Throws error 500

### ISSUE THREAD

**Issue by abhishek-sharma8** [arapurayil/utube#5]
This is awesome. Unfortunately, it only worked fine in the beginning (in September) but then it stopped. I tried with a few channels and it didn't work. Even the link you have provided in the readme isn't working. Could you please help. 

![image](https://user-images.githubusercontent.com/47742249/139581219-e3bcba0f-ad67-4c57-8b16-3b7979f04231.png)

**Comment by arapurayil** [comment]
@JemmySailesh had also reported [this](https://github.com/arapurayil/utube/issues/4). This is a sort of strange bug affecting mostly CF locations in India. Will try to find a solution to this. Meanwhile I've adapted the code to vercel platform.

https://vutube.vercel.app/api/<channel_id or video_id>/master.m3u8

**Comment by abhishek-sharma8** [comment]
The Vercel app shows this. Even tried using Cloudflare, Google DNS and VPN from US location and it is still the same. 
![image](https://user-images.githubusercontent.com/47742249/139838066-8ece3d50-924c-45b9-aefc-ad1198bac86d.png)

**Comment by arapurayil** [comment]
Is this also happening with other channels?
Update: This video is apparently blocked in US. Check [here](https://watannetwork.com/tools/blocked/) and [here](https://polsy.org.uk/stuff/ytrestrict.cgi). As the Vercel serverless function is served from Washington DC,US it won't work for videos blocked in US.
BTW did you check the cloudflare workers version of the app? I've made a few changes there.

**Comment by abhishek-sharma8** [comment]
It is now working for some channels and not working for some.
**Not working for these channels.**
UCt4t-jeY85JegMlZ-E5UWtA (Not working with vercel but working with Cloudflare. Maybe geo-blocked)
UCYPvAwZP8pZhSMW8qs7cVCw (Not working with vercel but working with Cloudflare. Maybe geo-blocked)
UC8p1vwvWtl6T73JiExfWs1g (Not working with vercel or cloudflare)

**Working for these**
UCIvaYmXn910QMdemBG3v1pQ (Working with both)
UCRWFSbif-RFENbBrSiez1DA (Working with both)

Edit: The change you made seems to have fixed the issues with the channels I needed. Thank you so much.
